//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gb_Policymaster
    {
        public string policy_code { get; set; }
        public string policy_oldcode { get; set; }
        public string cm_code { get; set; }
        public string cm_sp_code { get; set; }
        public string policy_branch { get; set; }
        public string Policy_Name { get; set; }
        public string policy_agentcode { get; set; }
        public Nullable<System.DateTime> Policy_inpt_date { get; set; }
        public Nullable<System.DateTime> Policy_effdate { get; set; }
        public Nullable<System.DateTime> policy_expdate { get; set; }
        public Nullable<System.DateTime> policy_rendate { get; set; }
        public Nullable<System.DateTime> policy_trandate { get; set; }
        public string policy_desc { get; set; }
        public string policy_delmarker { get; set; }
        public string policy_endorsno { get; set; }
        public Nullable<double> policy_totsumins { get; set; }
        public Nullable<double> policy_totannprem { get; set; }
        public Nullable<double> policy_totprem { get; set; }
        public string policy_fleetind { get; set; }
        public Nullable<int> policy_totveh { get; set; }
        public string policy_ref { get; set; }
        public string Policy_brokslipno { get; set; }
        public string subclass { get; set; }
        public string policy_direct { get; set; }
        public string policy_serialno { get; set; }
        public string policy_year { get; set; }
        public string policy_class { get; set; }
        public Nullable<decimal> Policy_fig_guarantee { get; set; }
        public Nullable<decimal> Policy_fig_lLoss { get; set; }
        public string policy_type { get; set; }
        public string policy_mar_type { get; set; }
        public Nullable<short> policy_clm_no { get; set; }
        public string Policy_Ind { get; set; }
        public string policy_endno { get; set; }
        public string CURR_cODE { get; set; }
        public string Policy_month { get; set; }
        public Nullable<double> curr_exchange { get; set; }
        public string policy_brokslip { get; set; }
        public string ind { get; set; }
        public string policy_staff_agent { get; set; }
        public Nullable<double> Policy_addition { get; set; }
        public Nullable<double> Policy_discount { get; set; }
        public Nullable<double> Policy_return { get; set; }
        public Nullable<double> Policy_deposit { get; set; }
        public string telephone { get; set; }
    }
}
