
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class accchart
{

    public string acctcode1 { get; set; }

    public string acctcode2 { get; set; }

    public string acctcode3 { get; set; }

    public string acctcode4 { get; set; }

    public string acctcode5 { get; set; }

    public string acctcode6 { get; set; }

    public string acctnumber { get; set; }

    public string description { get; set; }

    public string acctcode7 { get; set; }

    public string oldnumber { get; set; }

    public string acctype { get; set; }

    public string acctsubtype { get; set; }

    public string address { get; set; }

    public string effdate { get; set; }

    public string ledgerpasswd { get; set; }

    public string ledgerpasswd2 { get; set; }

    public string subcode { get; set; }

    public string blgroup1 { get; set; }

    public string blgroup2 { get; set; }

    public string blgroup3 { get; set; }

    public string blgroup4 { get; set; }

    public string blgroupdes1 { get; set; }

    public string blgroupdes2 { get; set; }

    public string blgroupdes3 { get; set; }

    public string blgroupdes4 { get; set; }

    public string blsum1 { get; set; }

    public string blsum2 { get; set; }

    public string blsum3 { get; set; }

    public string blsum4 { get; set; }

    public string blsumdesc1 { get; set; }

    public string blsumdesc2 { get; set; }

    public string blsumdesc3 { get; set; }

    public string blsumdesc4 { get; set; }

    public string cfgroup1 { get; set; }

    public string cfgroup2 { get; set; }

    public string cfgroup3 { get; set; }

    public string cfgroup4 { get; set; }

    public string cfgroupdes1 { get; set; }

    public string cfgroupdes2 { get; set; }

    public string cfgroupdes3 { get; set; }

    public string cfgroupdes4 { get; set; }

    public string cfsumdesc1 { get; set; }

    public string cfsumdesc2 { get; set; }

    public string cfsumdesc3 { get; set; }

    public string cfsumdesc4 { get; set; }

    public string createdby { get; set; }

    public Nullable<System.DateTime> datecreated { get; set; }

    public string address1 { get; set; }

    public string address2 { get; set; }

    public string address3 { get; set; }

    public string telephone { get; set; }

    public string email { get; set; }

    public string trade { get; set; }

    public Nullable<System.DateTime> dateblocked { get; set; }

}

}
