
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_PublicHoliday
{

    public long Id { get; set; }

    public string HolidayName { get; set; }

    public Nullable<int> Holidayday { get; set; }

    public Nullable<int> holidaymonth { get; set; }

    public string HolidayMsg { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> IsActive { get; set; }

}

}
