
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_premrateRules
{

    public long Id { get; set; }

    public Nullable<decimal> Interest { get; set; }

    public Nullable<decimal> CommRate { get; set; }

    public Nullable<decimal> Mkt_CommRate { get; set; }

    public Nullable<decimal> IntrBound { get; set; }

    public Nullable<decimal> CommBound { get; set; }

    public Nullable<int> PremRateId { get; set; }

}

}
