
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_premrate
{

    public int Id { get; set; }

    public int poltypeId { get; set; }

    public Nullable<int> grpcode { get; set; }

    public string period { get; set; }

    public Nullable<decimal> interest { get; set; }

    public Nullable<decimal> commrate { get; set; }

    public Nullable<decimal> retention { get; set; }

    public string mkt_commrate { get; set; }

    public Nullable<System.DateTime> Datecreated { get; set; }

    public string CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual fl_poltype fl_poltype { get; set; }

}

}
