
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_password
{

    public fl_password()
    {

        this.UserSessions = new HashSet<UserSession>();

        this.UserRoles = new HashSet<UserRole>();

    }


    public long Id { get; set; }

    public string userid { get; set; }

    public string userpassword { get; set; }

    public string Name { get; set; }

    public string userdept { get; set; }

    public string createdby { get; set; }

    public Nullable<System.DateTime> datecreated { get; set; }

    public Nullable<System.DateTime> expirydate { get; set; }

    public Nullable<System.DateTime> passworddate { get; set; }

    public Nullable<System.DateTime> Deleteddate { get; set; }

    public string Deletedby { get; set; }

    public Nullable<System.DateTime> modifydate { get; set; }

    public string modifyby { get; set; }

    public Nullable<System.DateTime> lastlogindate { get; set; }

    public Nullable<Flex.Data.Enum.UserStatus> status { get; set; }

    public Nullable<int> branch { get; set; }

    public string mobile { get; set; }

    public string email { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual ICollection<UserSession> UserSessions { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; }

}

}
