
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_receiptcontrol
{

    public int Id { get; set; }

    public Nullable<int> PolTypeId { get; set; }

    public Nullable<Flex.Data.Enum.PaymentMethod> PaymentMethod { get; set; }

    public string Income_ledger { get; set; }

    public string Bank_ledger { get; set; }

    public string BankAccount { get; set; }

    public string Bankname { get; set; }

    public Nullable<int> Receiptcounter { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<long> CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<long> ModifiedBy { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual fl_poltype fl_poltype { get; set; }

}

}
