

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class FlexEntities : DbContext
{
    public FlexEntities()
        : base("name=FlexEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CustomerUser> CustomerUsers { get; set; }

    public virtual DbSet<fl_password> fl_password { get; set; }

    public virtual DbSet<NextofKin_BeneficiaryStaging> NextofKin_BeneficiaryStaging { get; set; }

    public virtual DbSet<UserSession> UserSessions { get; set; }

    public virtual DbSet<CustomerPolicy> CustomerPolicies { get; set; }

    public virtual DbSet<PendingEmail> PendingEmails { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Tab> Tabs { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    public virtual DbSet<Portlet> Portlets { get; set; }

    public virtual DbSet<fl_system> fl_system { get; set; }

    public virtual DbSet<fl_poltype> fl_poltype { get; set; }

    public virtual DbSet<fl_pendingSMS> fl_pendingSMS { get; set; }

    public virtual DbSet<fl_location> fl_location { get; set; }

    public virtual DbSet<fl_policyinput> fl_policyinput { get; set; }

    public virtual DbSet<fl_receiptcontrol> fl_receiptcontrol { get; set; }

    public virtual DbSet<PersonalDetailsStaging> PersonalDetailsStagings { get; set; }

    public virtual DbSet<accchart> acccharts { get; set; }

    public virtual DbSet<ac_costCenter> ac_costCenter { get; set; }

    public virtual DbSet<fl_agents> fl_agents { get; set; }

    public virtual DbSet<LinkRole> LinkRoles { get; set; }

    public virtual DbSet<vwPolicy> vwPolicies { get; set; }

    public virtual DbSet<OnlineReciept> OnlineReciepts { get; set; }

    public virtual DbSet<fl_premrateRules> fl_premrateRules { get; set; }

    public virtual DbSet<fl_payclaim> fl_payclaim { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<fl_grouptype> fl_grouptype { get; set; }

    public virtual DbSet<fl_payinput> fl_payinput { get; set; }

    public virtual DbSet<fl_payhistory> fl_payhistory { get; set; }

    public virtual DbSet<ClaimRequest> ClaimRequests { get; set; }

    public virtual DbSet<fl_state> fl_state { get; set; }

    public virtual DbSet<ac_rctheader> ac_rctheader { get; set; }

    public virtual DbSet<fl_payinput2> fl_payinput2 { get; set; }

    public virtual DbSet<fl_translog> fl_translog { get; set; }

    public virtual DbSet<ac_rctdetails> ac_rctdetails { get; set; }

    public virtual DbSet<fl_PublicHoliday> fl_PublicHoliday { get; set; }

    public virtual DbSet<vProduction> vProductions { get; set; }

    public virtual DbSet<vwPolicyHistory> vwPolicyHistories { get; set; }

    public virtual DbSet<fl_premrate> fl_premrate { get; set; }

}

}

