
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PendingEmail
{

    public long ID { get; set; }

    public string Subject { get; set; }

    public System.DateTime DueDate { get; set; }

    public string Body { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string Bcc { get; set; }

    public string CC { get; set; }

    public string ErrorMessage { get; set; }

    public Nullable<bool> IsBodyHtml { get; set; }

    public string ReplyTo { get; set; }

    public string Sender { get; set; }

    public Nullable<int> Retries { get; set; }

    public string Priority { get; set; }

    public Nullable<bool> ThrewException { get; set; }

    public Nullable<int> RetryCount { get; set; }

    public Nullable<bool> IsSent { get; set; }

}

}
