
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vwPolicy
{

    public string policyno { get; set; }

    public Nullable<decimal> premium { get; set; }

    public string poltype { get; set; }

    public Nullable<int> location { get; set; }

    public string telephone { get; set; }

    public string email { get; set; }

    public string surname { get; set; }

    public string othername { get; set; }

    public Nullable<decimal> balance { get; set; }

    public Nullable<Flex.Data.Enum.Status> status { get; set; }

    public string agentcode { get; set; }

    public string address { get; set; }

    public long srn { get; set; }

    public string locdesc { get; set; }

    public string agentname { get; set; }

    public Nullable<System.DateTime> accdate { get; set; }

    public string title { get; set; }

    public string exitdate { get; set; }

    public Nullable<int> agentLocation { get; set; }

}

}
