//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSerialNumberGenerator.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISerialNumber")]
    public interface ISerialNumber {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerialNumber/GetNextNumber", ReplyAction="http://tempuri.org/ISerialNumber/GetNextNumberResponse")]
        string GetNextNumber(string contextKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerialNumber/GetNextNumber", ReplyAction="http://tempuri.org/ISerialNumber/GetNextNumberResponse")]
        System.Threading.Tasks.Task<string> GetNextNumberAsync(string contextKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISerialNumberChannel : TestSerialNumberGenerator.ServiceReference1.ISerialNumber, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerialNumberClient : System.ServiceModel.ClientBase<TestSerialNumberGenerator.ServiceReference1.ISerialNumber>, TestSerialNumberGenerator.ServiceReference1.ISerialNumber {
        
        public SerialNumberClient() {
        }
        
        public SerialNumberClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SerialNumberClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialNumberClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SerialNumberClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetNextNumber(string contextKey) {
            return base.Channel.GetNextNumber(contextKey);
        }
        
        public System.Threading.Tasks.Task<string> GetNextNumberAsync(string contextKey) {
            return base.Channel.GetNextNumberAsync(contextKey);
        }
    }
}
