
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class ac_costCenter
{

    public ac_costCenter()
    {

        this.fl_agents = new HashSet<fl_agents>();

    }


    public int Id { get; set; }

    public string Code { get; set; }

    public string Desc { get; set; }



    public virtual ICollection<fl_agents> fl_agents { get; set; }

}

}
