//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_jvheader
    {
        public string coycode { get; set; }
        public string branchcode { get; set; }
        public string jvh_number { get; set; }
        public string jvh_type { get; set; }
        public string jvh_refnumber { get; set; }
        public string jvh_date { get; set; }
        public Nullable<decimal> jvh_debit { get; set; }
        public Nullable<decimal> jvh_credit { get; set; }
        public Nullable<decimal> jvh_total { get; set; }
        public string jvh_remark { get; set; }
        public bool jvh_indicator { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public string deletedind { get; set; }
    }
}
