//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_jvdetails
    {
        public string coycode { get; set; }
        public string branchcode { get; set; }
        public string jv_number { get; set; }
        public string jv_account { get; set; }
        public string jv_code { get; set; }
        public string jv_unitcode { get; set; }
        public Nullable<decimal> jv_debit { get; set; }
        public Nullable<decimal> jv_credit { get; set; }
        public string jv_remark { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string deletedby { get; set; }
        public Nullable<System.DateTime> datedeleted { get; set; }
    }
}
