//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_pcvheader
    {
        public string coycode { get; set; }
        public string branchcode { get; set; }
        public string pcvh_number { get; set; }
        public string pcvh_refnumber { get; set; }
        public string pcvh_cheque { get; set; }
        public string pcvh_date { get; set; }
        public string pcvh_policy { get; set; }
        public string pcvh_bank { get; set; }
        public Nullable<decimal> pcvh_debit { get; set; }
        public Nullable<decimal> pcvh_credit { get; set; }
        public Nullable<decimal> pcvh_total { get; set; }
        public string pcvh_remark { get; set; }
        public bool pcvh_indicator { get; set; }
        public string deleteind { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
    }
}
