//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_rctdetails
    {
        public string rct_number { get; set; }
        public string rct_account { get; set; }
        public string rct_type { get; set; }
        public string rct_code { get; set; }
        public Nullable<decimal> rct_debit { get; set; }
        public Nullable<decimal> rct_credit { get; set; }
        public string rct_remark { get; set; }
        public string rct_bank { get; set; }
        public string coy_code { get; set; }
        public string Branch_code { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<System.DateTime> datedeleted { get; set; }
        public string deletedby { get; set; }
        public string deletemarker { get; set; }
        public string rct_class { get; set; }
        public Nullable<decimal> rct_premium { get; set; }
        public Nullable<decimal> rct_premloan { get; set; }
        public Nullable<decimal> rct_policyloan { get; set; }
        public Nullable<decimal> rct_othercharge { get; set; }
        public string rct_grossnet { get; set; }
        public string rct_partfull { get; set; }
    }
}
