//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_rctheader
    {
        public string coy_code { get; set; }
        public string Branch_code { get; set; }
        public string rcth_unitcode { get; set; }
        public string rcth_number { get; set; }
        public string rcth_name { get; set; }
        public string rcth_address { get; set; }
        public string rcth_refnumber { get; set; }
        public string rcth_cheque { get; set; }
        public string rcth_class { get; set; }
        public string rcth_type { get; set; }
        public string rcth_date { get; set; }
        public string rcth_policy { get; set; }
        public string rcth_bank { get; set; }
        public Nullable<decimal> rcth_debit { get; set; }
        public Nullable<decimal> rcth_credit { get; set; }
        public Nullable<decimal> rcth_total { get; set; }
        public string rcth_remark { get; set; }
        public bool rcth_indicator { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
        public Nullable<System.DateTime> datedeleted { get; set; }
        public string deletedby { get; set; }
        public string naira { get; set; }
        public string kobo { get; set; }
    }
}
