//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_agents
    {
        public long Id { get; set; }
        public string agentcode { get; set; }
        public string agentname { get; set; }
        public Nullable<int> locationId { get; set; }
        public Nullable<int> agenttype { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public string modifiedby { get; set; }
        public string agentaddr { get; set; }
        public string agentphone { get; set; }
        public Nullable<int> status { get; set; }
        public string exitdate { get; set; }
    
        public virtual ac_costCenter ac_costCenter { get; set; }
    }
}
