//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_agents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fl_agents()
        {
            this.UserSessions = new HashSet<UserSession>();
        }
    
        public long Id { get; set; }
        public string agentcode { get; set; }
        public string agentname { get; set; }
        public Nullable<int> locationId { get; set; }
        public Nullable<int> agenttype2 { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public string modifiedby { get; set; }
        public string agentaddr { get; set; }
        public string agentphone { get; set; }
        public Nullable<int> status { get; set; }
        public string exitdate { get; set; }
        public string agenttype { get; set; }
        public string password { get; set; }
    
        public virtual ac_costCenter ac_costCenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}
