//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_gpayclaim
    {
        public string poltype { get; set; }
        public string grpcode { get; set; }
        public string pcn { get; set; }
        public string receiptno { get; set; }
        public string period { get; set; }
        public string policyno { get; set; }
        public Nullable<System.DateTime> orig_date { get; set; }
        public Nullable<System.DateTime> trandate { get; set; }
        public Nullable<float> gir { get; set; }
        public Nullable<decimal> loanamt { get; set; }
        public string doctype { get; set; }
        public Nullable<decimal> psopen { get; set; }
        public Nullable<decimal> psamount { get; set; }
        public Nullable<decimal> pscur_intr { get; set; }
        public Nullable<decimal> pscumul_intr { get; set; }
        public Nullable<decimal> eropen { get; set; }
        public Nullable<decimal> eramount { get; set; }
        public Nullable<decimal> ercur_intr { get; set; }
        public Nullable<decimal> ercumul_intr { get; set; }
        public Nullable<decimal> eeopen { get; set; }
        public Nullable<decimal> eeamount { get; set; }
        public Nullable<decimal> eecur_intr { get; set; }
        public Nullable<decimal> eecumul_intr { get; set; }
        public Nullable<decimal> avopen { get; set; }
        public Nullable<decimal> avamount { get; set; }
        public Nullable<decimal> avcur_intr { get; set; }
        public Nullable<decimal> avcumul_intr { get; set; }
        public Nullable<decimal> ccopen { get; set; }
        public Nullable<decimal> ccamount { get; set; }
        public Nullable<decimal> cccur_intr { get; set; }
        public Nullable<decimal> cccumul_intr { get; set; }
        public Nullable<decimal> pscopen { get; set; }
        public Nullable<decimal> pscamount { get; set; }
        public Nullable<decimal> psccur_intr { get; set; }
        public Nullable<decimal> psccumul_intr { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> dateupdated { get; set; }
    }
}
