//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_pendingSMS
    {
        public int srn { get; set; }
        public string telephone { get; set; }
        public string message { get; set; }
        public Nullable<bool> isSent { get; set; }
        public Nullable<int> retrycount { get; set; }
    }
}
