
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_policyinput
{

    public long srn { get; set; }

    public string policyno { get; set; }

    public string pcn { get; set; }

    public string grpcode { get; set; }

    public string sex { get; set; }

    public string title { get; set; }

    public string surname { get; set; }

    public string othername { get; set; }

    public string peradd { get; set; }

    public string dob { get; set; }

    public string nok { get; set; }

    public Nullable<System.DateTime> datecreated { get; set; }

    public string createdby { get; set; }

    public Nullable<System.DateTime> datemodified { get; set; }

    public string modifiedby { get; set; }

    public Nullable<System.DateTime> accdate { get; set; }

    public string quoteno { get; set; }

    public string poltype { get; set; }

    public string exitdate { get; set; }

    public Nullable<int> location { get; set; }

    public string agentcode { get; set; }

    public string email { get; set; }

    public Nullable<decimal> premium { get; set; }

    public string telephone { get; set; }

    public string pinword { get; set; }

    public string religion { get; set; }

    public Nullable<int> status { get; set; }

    public string pwd { get; set; }

    public byte[] PictureFile { get; set; }



    public virtual fl_location fl_location { get; set; }

}

}
