//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_prgaccess
    {
        public string userid { get; set; }
        public string formcode { get; set; }
        public string descr { get; set; }
        public string accesscode { get; set; }
        public string createdby { get; set; }
    }
}
