//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_premrate_temp
    {
        public string poltype { get; set; }
        public string grpcode { get; set; }
        public string period { get; set; }
        public string interest { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string commrate { get; set; }
        public string retention { get; set; }
        public string mkt_commrate { get; set; }
        public string interest2 { get; set; }
        public string interest3 { get; set; }
        public string commrate3 { get; set; }
        public string commrate2 { get; set; }
        public string mkt_commrate3 { get; set; }
        public string mkt_commrate2 { get; set; }
        public Nullable<decimal> intr_bound { get; set; }
        public Nullable<decimal> intr_bound2 { get; set; }
        public Nullable<decimal> intr_bound3 { get; set; }
        public Nullable<decimal> comm_bound { get; set; }
        public Nullable<decimal> comm_bound2 { get; set; }
        public Nullable<decimal> comm_bound3 { get; set; }
    }
}
