//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_premrate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fl_premrate()
        {
            this.fl_premrateRules = new HashSet<fl_premrateRules>();
        }
    
        public int Id { get; set; }
        public int poltypeId { get; set; }
        public Nullable<int> grpcodeId { get; set; }
        public string period { get; set; }
        public Nullable<decimal> interest { get; set; }
        public Nullable<decimal> commrate { get; set; }
        public Nullable<decimal> retention { get; set; }
        public string mkt_commrate { get; set; }
        public Nullable<System.DateTime> Datecreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string poltype { get; set; }
        public Nullable<int> grpcode { get; set; }
        public string interest2 { get; set; }
        public string interest3 { get; set; }
        public string commrate3 { get; set; }
        public string commrate2 { get; set; }
        public string mkt_commrate3 { get; set; }
        public string mkt_commrate2 { get; set; }
        public Nullable<decimal> intr_bound { get; set; }
        public Nullable<decimal> intr_bound2 { get; set; }
        public Nullable<decimal> intr_bound3 { get; set; }
        public Nullable<decimal> comm_bound { get; set; }
        public Nullable<decimal> comm_bound2 { get; set; }
        public Nullable<decimal> comm_bound3 { get; set; }
    
        public virtual fl_grouptype fl_grouptype { get; set; }
        public virtual fl_poltype fl_poltype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fl_premrateRules> fl_premrateRules { get; set; }
    }
}
