//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_payinput
    {
        public long Id { get; set; }
        public string policyno { get; set; }
        public string receiptno { get; set; }
        public string type { get; set; }
        public string grpcode { get; set; }
        public string pcn { get; set; }
        public Nullable<bool> reverseind { get; set; }
        public Nullable<System.DateTime> trandate { get; set; }
        public System.DateTime effdate { get; set; }
        public Nullable<decimal> totamt { get; set; }
        public string chequeno { get; set; }
        public string payindicator { get; set; }
        public string status { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string poltype { get; set; }
    }
}
