
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class fl_poltype
{

    public fl_poltype()
    {

        this.fl_receiptcontrol = new HashSet<fl_receiptcontrol>();

        this.PersonalDetailsStagings = new HashSet<PersonalDetailsStaging>();

        this.fl_premrate = new HashSet<fl_premrate>();

    }


    public int Id { get; set; }

    public string poltype { get; set; }

    public string poldesc { get; set; }

    public string actype { get; set; }

    public Nullable<int> term { get; set; }

    public Nullable<int> matage { get; set; }

    public Nullable<decimal> maxloan { get; set; }

    public string income_account { get; set; }

    public string liability_account { get; set; }

    public string expense_account { get; set; }

    public string vat_account { get; set; }

    public Nullable<System.DateTime> Datecreated { get; set; }

    public Nullable<System.DateTime> CreatedBy { get; set; }

    public Nullable<System.DateTime> DateModified { get; set; }

    public Nullable<System.DateTime> ModifiedBy { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string code { get; set; }



    public virtual ICollection<fl_receiptcontrol> fl_receiptcontrol { get; set; }

    public virtual ICollection<PersonalDetailsStaging> PersonalDetailsStagings { get; set; }

    public virtual ICollection<fl_premrate> fl_premrate { get; set; }

}

}
