//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fl_system
    {
        public int Id { get; set; }
        public string coycode { get; set; }
        public string coyname { get; set; }
        public string coyaddress { get; set; }
        public string town { get; set; }
        public string lg { get; set; }
        public string state { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public string box { get; set; }
        public string processyear { get; set; }
        public string processmonth { get; set; }
        public string installdate { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public string serialnumber { get; set; }
        public string reassurance { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
