
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class NextofKin_BeneficiaryStaging
{

    public long Id { get; set; }

    public string RegNo { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public Flex.Data.Enum.Type Type { get; set; }

    public Nullable<System.DateTime> Dob { get; set; }

    public string RelationShip { get; set; }

    public Flex.Data.Enum.Category Category { get; set; }

    public Nullable<long> PersonalDetailsStagingId { get; set; }

    public Nullable<decimal> Proportion { get; set; }

    public Nullable<Flex.Data.Enum.ApprovalStatus> ApprovalStatus { get; set; }

    public Nullable<bool> IsSynched { get; set; }

    public Nullable<long> PolicyId { get; set; }



    public virtual PersonalDetailsStaging PersonalDetailsStaging { get; set; }

}

}
