//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public string Policyno { get; set; }
        public string period { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> NotificationType { get; set; }
        public Nullable<int> NotificationFor { get; set; }
    }
}
