//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineReciept
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ReceiptNo { get; set; }
        public Nullable<int> PaymentChannel { get; set; }
        public Nullable<decimal> InitialAmount { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
        public string Product { get; set; }
        public string Policyno { get; set; }
        public Nullable<bool> IsSynched { get; set; }
        public Nullable<int> TransactionStatus { get; set; }
        public string InitialResponseCode { get; set; }
        public Nullable<System.DateTime> InitialPaymentDate { get; set; }
        public string IntialResponseDecription { get; set; }
        public string FinalResponseCode { get; set; }
        public Nullable<System.DateTime> FinalPaymentDate { get; set; }
        public string FinalResponseDecription { get; set; }
    }
}
