//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetailsStaging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalDetailsStaging()
        {
            this.NextofKin_BeneficiaryStaging = new HashSet<NextofKin_BeneficiaryStaging>();
        }
    
        public long Id { get; set; }
        public string RegNo { get; set; }
        public string Surname { get; set; }
        public string OtherNames { get; set; }
        public string ResAddress { get; set; }
        public string OffAddress { get; set; }
        public string PosAddress { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string Occupation { get; set; }
        public Nullable<decimal> ContribAmount { get; set; }
        public string ContribFreq { get; set; }
        public System.DateTime CommencementDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> PolicyType { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<bool> IsSynched { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<int> Location { get; set; }
        public byte[] PictureFile { get; set; }
        public string IdentityNumber { get; set; }
        public string IdentityType { get; set; }
        public byte[] signature { get; set; }
        public string agentcode { get; set; }
        public Nullable<bool> TermsAndConditions { get; set; }
        public string photopath { get; set; }
    
        public virtual fl_poltype fl_poltype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NextofKin_BeneficiaryStaging> NextofKin_BeneficiaryStaging { get; set; }
    }
}
