
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Tab
{

    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<int> PortletId { get; set; }

    public string icon { get; set; }

    public string Controller { get; set; }

    public string Action { get; set; }

    public Nullable<int> Order { get; set; }

    public string View { get; set; }



    public virtual Portlet Portlet { get; set; }

}

}
