//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSession
    {
        public long Id { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<long> CustomerUserID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> LastAccessed { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
        public Nullable<int> SessionStatus { get; set; }
        public Nullable<long> AccessCount { get; set; }
        public string Token { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual CustomerUser CustomerUser { get; set; }
        public virtual fl_password fl_password { get; set; }
    }
}
