//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flex.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProduction
    {
        public string policyno { get; set; }
        public string agentname { get; set; }
        public string agentcode { get; set; }
        public Nullable<System.DateTime> accdate { get; set; }
        public string receiptno { get; set; }
        public string chequeno { get; set; }
        public Nullable<decimal> totamt { get; set; }
        public string trandate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string surname { get; set; }
        public string othername { get; set; }
        public string title { get; set; }
        public Nullable<int> location { get; set; }
        public Nullable<int> agentLocation { get; set; }
        public Nullable<System.DateTime> trandate_w { get; set; }
    }
}
