
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Flex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class vwPolicyHistory
{

    public string policyno { get; set; }

    public string receiptno { get; set; }

    public string period { get; set; }

    public Nullable<System.DateTime> trandate { get; set; }

    public Nullable<decimal> amount { get; set; }

    public Nullable<decimal> cumul_intr { get; set; }

    public string Name { get; set; }

    public string locdesc { get; set; }

    public string doctype { get; set; }

    public Nullable<decimal> cur_intr { get; set; }

    public float gir { get; set; }

    public string title { get; set; }

    public Nullable<System.DateTime> orig_date { get; set; }

    public string telephone { get; set; }

}

}
